## Exemplo SVM - Classificação de flores - testando kernels

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
%matplotlib inline
from sklearn.svm import SVC

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

X = dataset.drop('Class', axis=1)
y = dataset['Class']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35, random_state=100,stratify=y)

### Kernel linear

In [ ]:
model = SVC(kernel='linear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[18  0  0]
 [ 0 17  0]
 [ 0  2 16]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        18
Iris-versicolor       0.89      1.00      0.94        17
 Iris-virginica       1.00      0.89      0.94        18

       accuracy                           0.96        53
      macro avg       0.96      0.96      0.96        53
   weighted avg       0.97      0.96      0.96        53



### Kernel polynomial

In [ ]:
model = SVC(kernel='poly', degree=5)
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=5, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
model = SVC(kernel='poly', degree=5)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[18  0  0]
 [ 0 16  1]
 [ 0  5 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        18
Iris-versicolor       0.76      0.94      0.84        17
 Iris-virginica       0.93      0.72      0.81        18

       accuracy                           0.89        53
      macro avg       0.90      0.89      0.88        53
   weighted avg       0.90      0.89      0.89        53



### Kernel Radial (RBF) - Gaussiano

In [ ]:
model = SVC(kernel='rbf')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[18  0  0]
 [ 0 16  1]
 [ 0  4 14]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        18
Iris-versicolor       0.80      0.94      0.86        17
 Iris-virginica       0.93      0.78      0.85        18

       accuracy                           0.91        53
      macro avg       0.91      0.91      0.90        53
   weighted avg       0.91      0.91      0.91        53



### Kernel Sigmoidal

In [ ]:
model = SVC(kernel='sigmoid')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0 18  0]
 [ 0 17  0]
 [ 0 18  0]]
                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        18
Iris-versicolor       0.32      1.00      0.49        17
 Iris-virginica       0.00      0.00      0.00        18

       accuracy                           0.32        53
      macro avg       0.11      0.33      0.16        53
   weighted avg       0.10      0.32      0.16        53



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


baseado no exemplo apresentado em: https://stackabuse.com/implementing-svm-and-kernel-svm-with-pythons-scikit-learn/